### ISSUE TITLE
shelljs in node docker image returns /bin/sh: 1: Syntax error: Unterminated quoted string  

### ISSUE THREAD

**Issue by thebetterjort** [shelljs/shelljs#989]
Any ideas on how to get this working in docker:node?

```
version: '3'
volumes:
  nodemodulesDC:
    external: true

services:
  directory-sync:
    image: node:latest
    container_name: directory-sync
    volumes:
      - nodemodulesDC:/usr/src/web/node_modules
      - .:/usr/src/web
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/web
    command:  bash -c "yarn config set strict-ssl false; yarn global add shelljs; yarn global add node-cron; yarn add json2graphql; node start.js"
 
```

```

cron.schedule("* * * * *", function() {
  console.log("running a task every minute");
  if (shell.exec('json2graphql http://localhost:8080 --db=./index.js --overwrite"').code !== 0) {
  shell.echo('Error: json2graphql failed');
  shell.exit(1);
}
});
```
